# Setup
title: fr3d1s4nm4r
description: CTFs, Hackthebox y temas relacionados con red teaming
url: https://fredisanmar.github.io/
paginate: 5
permalink: pretty
avatar: logo.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
#twitter:
#  username: fr3d1s4nm4r
#  card: summary
logo: logo.png
social:
  name: fr3d1s4nm4r
  links:
    - https://www.hackthebox.eu/profile/231883
    - https://github.com/fredisanmar
google_site_verification: rs9Q35s9q6im0kqyyEAXQkSvxaUtAOq-L7ZZr6SGjNQ
lang: es

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-ZPC9HZQY58

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: fr3d1s4nm4r
  url: https://github.com/fredisanmar
  email: fr3d1s4nm4r@gmail.com
